
data_config: "config/final_evaluation/evaluation_data_config.yaml"
save_results: True #True


###########
## Paths ##
###########
predictions_dir: "results/final_evaluation/predictions"
evaluation_dir: "results/final_evaluation/evaluation"
models_options:
  spectrogram_overlap: 0.75
  smooth_predictions: True
  smooth_factor: 3
  input_height: 32
  # repredict: True
  # A: 0.05

evaluators_options:
  draw_plots: False
  draw_global_plots: False
  plots: ["distances", "pr_curve", "roc"] #"separate_distances", "roc"
  phenology_databases: ["full_summer1", "ENAB"]


id: final_evaluation

evaluators:
  # - type: "phenology"
  #   method: direct
  #   scenarios:
  #     activity_threshold:
  #       start: 0.65
  #       end: 0.8
  #       step: 0.01
  #   # end_threshold: 0.3
  #   # min_duration: 0.4
  #   # gtc_threshold: 0
  #   # dtc_threshold: 0
  #   daily_aggregation: "sum"
  # - type: "phenology"
  #   method: standard
  #   activity_threshold: 0.94
  #   end_threshold: 0.5
  #   min_duration: 0.4
  #   gtc_threshold: 0
  #   dtc_threshold: 0
  #   daily_aggregation: "sum"
  # - type: "phenology"
  #   method: standard
  #   activity_threshold: 0.92
  #   end_threshold: 0.5
  #   min_duration: 0.4
  #   gtc_threshold: 0
  #   dtc_threshold: 0
  #   daily_aggregation: "sum"
  - type: "direct"
    activity_threshold: 0.8
  # - type: "standard"
  #   activity_threshold: 0.9
  #   end_threshold: 0.5
  #   min_duration: 0.4
  #   daily_aggregation: "sum"
  #   gtc_threshold: 0
  #   dtc_threshold: 0 
  # - type: "phenology"
  #   method: standard
  #   activity_threshold: 0.9
  #   end_threshold: 0.5
  #   min_duration: 0.4
  #   daily_aggregation: "sum"
  #   gtc_threshold: 0
  #   dtc_threshold: 0 


models_list_dir:  "resources/models"

models_list_options:
  model_dir:  "resources/models"
  ignore_parent_path: True
  batch_size: 64

databases_options:
  class_type: "biotic"
  spectrogram:
    n_mels: 32
    n_fft: 512
    sample_rate: "original"

# models_list_dir: "../resources/models"

# models_list_options:
#   model_dir: "../resources/models"
#   ignore_parent_path: True
#   batch_size: 64
#   reclassify: True
#   scenarios:
#     spectrogram_overlap: 0.95

model_ids:
  - DLBD_v2


databases:
  - name: full_summer1
  - name: citynet
  - name: nips4b
  - name: ENAB
  # - name: arctic_checked_split