
data_config: "config/evaluation_data_config.yaml"
save_results: True #True


###########
## Paths ##
###########
predictions_dir: "results/predictions"
evaluation_dir: "results/metrics/evaluation"
models_options:
  spectrogram_overlap: 0.75
  smooth_predictions: True
  input_height: 32
  # repredict: True
  # A: 0.05

evaluators_options:
  draw_plots: False
  draw_global_plots: False
  plots: ["distances", "pr_curve", "roc"] #"separate_distances", "roc"
  phenology_databases: ["full_summer_final", "ENAB_final"]


id: metrics_direct_positive_final

evaluators:
  # - type: "phenology"
  #   method: standard
  #   scenarios:
  #     activity_threshold:
  #       start: 0.5
  #       end: 0.99
  #       step: 0.01
  #     end_threshold:
  #       start: 0.1
  #       end: 0.5
  #       step: 0.1
  #     min_duration:
  #       start: 0.2
  #       end: 0.4
  #       step: 0.1
  #     daily_aggregation: "sum"
  - type: "phenology"
    method: "direct"
    scenarios:
      activity_threshold:
        start: 0.1
        end: 0.99
        step: 0.03
    # positive_only: True
    only_positives: True
      # remove_crows: [True, False]
    daily_aggregation: "sum"


models_list_dir:  "resources/models"

models_list_options:
  model_dir:  "resources/models"
  ignore_parent_path: True
  batch_size: 64

databases_options:
  class_type: "biotic"
  spectrogram:
    n_mels: 32
    n_fft: 512
    sample_rate: "original"


model_ids:
  - DLBD_v2


databases:
  - name: full_summer_final
  # - name: ENAB_final