
data_config: "config/evaluation_data_config.yaml"
save_results: True #True


###########
## Paths ##
###########
predictions_dir: "results/predictions"
evaluation_dir: "results/evaluation"
models_options:
  spectrogram_overlap: 0.75
  smooth_predictions: True
  smooth_factor: 3
  input_height: 32
  # repredict: True
  # A: 0.05

evaluators_options:
  draw_plots: False
  # draw_global_plots: True
  # plots: ["distances", "pr_curve", "roc", "tag_repartition", "detected_tags", "overlap_duration", "overlap_duration_bar"] #"separate_distances", "roc"
  phenology_databases: ["full_summer_final", "ENAB_final"]


id: paper_plots

evaluators:
  - type: "phenology"
    method: "direct"
    activity_threshold: 0.75
    scenarios:
      remove_crows: [True, False]


models_list_dir:  "/mnt/win/UMoncton/Doctorat/dev/phenol1/resources/models"

models_list_options:
  model_dir:  "/mnt/win/UMoncton/Doctorat/dev/phenol1/resources/models"
  ignore_parent_path: True
  batch_size: 64

databases_options:
  class_type: "biotic"
  spectrogram:
    n_mels: 32
    n_fft: 512
    sample_rate: "original"


model_ids:
  - DLBD_v2

databases:
  - name: full_summer_final
  - name: ENAB_final