
data_config: "config/evaluation_data_config.yaml"
save_results: True #True


###########
## Paths ##
###########
predictions_dir: "results/predictions"
evaluation_dir: "results/evaluation"
models_options:
  spectrogram_overlap: 0.75
  smooth_predictions: True
  smooth_factor: 3
  input_height: 32
  # repredict: True
  # A: 0.05

evaluators_options:
  draw_plots: True
  draw_global_plots: True
  plots: ["distances", "pr_curve", "roc"] #"separate_distances", "roc"
  phenology_databases: ["full_summer_final", "ENAB_final"]


id: final_evaluation

evaluators:
  # - type: "phenology"
  #   method: direct
  #   scenarios:
  #     activity_threshold:
  #       start: 0.65
  #       end: 0.8
  #       step: 0.01
  #   # end_threshold: 0.3
  #   # min_duration: 0.4
  #   # gtc_threshold: 0
  #   # dtc_threshold: 0
  #   daily_aggregation: "sum"
  # - type: "phenology"
  #   method: standard
  #   activity_threshold: 0.94
  #   end_threshold: 0.5
  #   min_duration: 0.4
  #   gtc_threshold: 0
  #   dtc_threshold: 0
  #   daily_aggregation: "sum"
  # - type: "phenology"
  #   method: standard
  #   activity_threshold: 0.92
  #   end_threshold: 0.5
  #   min_duration: 0.4
  #   gtc_threshold: 0
  #   dtc_threshold: 0
  #   daily_aggregation: "sum"
  - type: "phenology"
    method: "direct"
    scenarios:
      activity_threshold: [0.7, 0.75, 0.8, 0.85, 0.9]
  - type: phenology
    method: "standard"
    scenarios:
      activity_threshold: [0.8, 0.85, .9 , .95]
      end_threshold: [0.1, 0.2, 0.3, 0.5]
      min_duration: [0.2, 0.4]
    daily_aggregation: "sum"
    gtc_threshold: 0
    dtc_threshold: 0 
  # - type: "phenology"
  #   method: standard
  #   activity_threshold: 0.9
  #   end_threshold: 0.5
  #   min_duration: 0.4
  #   daily_aggregation: "sum"
  #   gtc_threshold: 0
  #   dtc_threshold: 0 


models_list_dir:  "/mnt/win/UMoncton/Doctorat/dev/phenol1/resources/models"

models_list_options:
  model_dir:  "/mnt/win/UMoncton/Doctorat/dev/phenol1/resources/models"
  ignore_parent_path: True
  batch_size: 64

databases_options:
  class_type: "biotic"
  spectrogram:
    n_mels: 32
    n_fft: 512
    sample_rate: "original"


model_ids:
  - DLBD_v2

databases:
  - name: full_summer_final
  # - name: citynet_final
  # - name: nips4b_final
  # - name: ENAB_final
  # - name: arctic_checked_final