
data_config: "config/evaluation_data_config.yaml"
save_results: True #True


###########
## Paths ##
###########
predictions_dir: "results/predictions"
evaluation_dir: "results/PR_curves"
models_options:
  spectrogram_overlap: 0.75
  smooth_predictions: True
  smooth_factor: 3
  input_height: 32
  # repredict: True
  # A: 0.05

evaluators_options:
  draw_plots: True
  draw_global_plots: True
  plots: ["distances", "pr_curve", "roc"] #"separate_distances", "roc"
  phenology_databases: ["full_summer_final", "ENAB_final"]


id: standard_pr_curves

evaluators:
  - type: "standard"
    do_PR_curve: True
    scenarios_PR_curve:
      activity_threshold:
        start: 0.05
        end: 0.99 
        step: 0.05
      end_threshold:
        start: 0.1
        end: 0.5
        step: 0.1
    daily_aggregation: "sum"
    end_threshold: 0.5
    min_duration: 0.3
    gtc_threshold: 0
    dtc_threshold: 0 


models_list_dir:  "/mnt/win/UMoncton/Doctorat/dev/phenol1/resources/models"

models_list_options:
  model_dir:  "/mnt/win/UMoncton/Doctorat/dev/phenol1/resources/models"
  ignore_parent_path: True
  batch_size: 64

databases_options:
  class_type: "biotic"
  spectrogram:
    n_mels: 32
    n_fft: 512
    sample_rate: "original"


model_ids:
  - DLBD_v2

databases:
  # - name: full_summer_final
  - name: citynet_final
  # - name: nips4b_final
  # - name: ENAB_final
  # - name: arctic_checked_final