
data_config: "config/presence/evaluation_data_config.yaml"
save_results: True #True

###########
## Paths ##
###########
predictions_dir: "results/presence/predictions"
evaluation_dir: "results/presence/evaluation"
models_options:
  spectrogram_overlap: 0.5
  smooth_predictions: True
  smooth_factor: 2
  # repredict: True
  # A: 0.05

evaluators_options:
  draw_plots: False
  draw_global_plots: False
  presence_databases: ["arctic_checked_all", "arctic_checked_split"]


id: checked_v2

evaluators:
  - type: presence
    method: "standard"
    activity_threshold: 0.92
    min_duration: 0.4
    end_threshold: 0.5
    dtc_threshold: 0
    gtc_threshold: 0

  # - type: presence
  #   method: direct
  #   activity_threshold: 0.7
  # - type: presence
  #   method: direct
  #   activity_threshold: 0.75

  # - type: presence
  #   method: "standard"
  #   activity_threshold: 0.9
  #   min_duration: 0.1
  #   end_threshold: 0.5


databases_options:
  class_type: "biotic"
  spectrogram:
    n_mels: 32
    n_fft: 512
    sample_rate: "original"


models_list_options:
  model_dir: "/home/vin/Doctorat/dev/phenol1/resources/models"
  ignore_parent_path: True
  batch_size: 64
  # scenarios:
  #   spectrogram_overlap: 0.5
    # smooth_factor: 20

model_ids:
  - DLBD
  - DLBD_v2
  # - DLBD_checked


databases:
  # - name: arctic_complete_final
  - name: arctic_checked_all
  # - name: full_summer1