#* All path can be relative to the root_dir or complete
# root_dir: other dirs will be relative to this one
data_dir: 'wavs'
tags_dir: 'tags'
training_dir: 'training'
validation_dir:  'validation'
test_dir: 'test'
dest_dir: '/mnt/win/UMoncton/Doctorat/data/dl_training/datasets'
save_intermediate: False

print_missing_classes: True
overwrite: False

subfolders:
  - type: "spectrogram"
    options: ["sample_rate", "type", "n_fft", "win_length", "hop_length"]

data_extensions:
  - ".wav"
  - ".WAV"
recursive: True

#* Tags files options
tags:
  print_missing_classes: True
  suffix: "-sceneRect.csv"
  columns:
    Label: "tag"
    Related: "related"
    LabelStartTime_Seconds: "tag_start"
    LabelEndTime_Seconds: "tag_end"
    overlap: "overlap"
    background: "background"
    noise: "noise"
    start: "tag_start"
    end: "tag_end"
  columns_type:
    overlap: "str"
  with_data: False


databases:
  #* All options found in data can be overriden in each iteration. If not found, default values
  #* from data will be used
    - name: 'citynet'
      root_dir: '/mnt/win/UMoncton/Doctorat/data/dl_training/raw/CityNet'
      data_by_type: True
      # spectrogram:
      #   sample_rate: 22050
      split:
        validation: 0.2
    - name: 'full_summer1'
      root_dir: '/mnt/win/UMoncton/Doctorat/data/dl_training/raw/full_summer_subset1/'
      data_dir: '/mnt/win/UMoncton/Doctorat/data/dl_training/raw/full_summer_subset1/'
      db_types: ["test"]
      overwrite: False
      tags:
        with_data: True
    - name: 'nips4b'
      root_dir: '/mnt/win/UMoncton/Doctorat/data/dl_training/raw/nips4b'
      data_dir: "/mnt/win/UMoncton/Doctorat/data/dl_training/raw/nips4b/wavs"
      tags_dir: "/mnt/win/UMoncton/Doctorat/data/dl_training/raw/nips4b/tags"
      data_by_type: True
      split:
        validation: 0.2
        test: 0.2
      tags:
        type: "nips4b"
    - name: 'ENAB'
      root_dir: '/home/vin/Doctorat/data/dl_training/raw/ENAB'
      data_dir: '/home/vin/Doctorat/data/dl_training/raw/ENAB'
      db_types: ["test"]
      overwrite: False
      tags:
        print_missing_classes: True
        filter_classes: False
        with_data: True
        suffix: ".Table.1.selections.txt"
        columns:
          Species: "tag"
          "Begin Time (s)": "tag_start"
          "End Time (s)": "tag_end"
    - name: 'arctic_checked'
      root_dir: "/home/vin/Doctorat/data/dl_training/raw/ArcticChecked/2018"
      data_dir: "/home/vin/Doctorat/data/dl_training/raw/ArcticChecked/2018"
      db_types: ["test"]
      # db_types: ["training", "validation"]
      tags:
        with_data: True
        suffix: "-tags.csv"
    - name: 'arctic_checked_all'
      root_dir: "/home/vin/Doctorat/data/dl_training/raw/ArcticChecked/filtered"
      data_dir: "/home/vin/Doctorat/data/dl_training/raw/ArcticChecked/filtered"
      db_types: ["test"]
      # db_types: ["training", "validation"]
      tags:
        with_data: True
        suffix: "-tags.csv"
    - name: 'arctic_checked_split'
      root_dir: "/home/vin/Doctorat/data/dl_training/raw/ArcticChecked/filtered"
      data_dir: "/home/vin/Doctorat/data/dl_training/raw/ArcticChecked/filtered"
      tags:
        with_data: True
        suffix: "-tags.csv"
      split:
        validation: 0.3
        test: 0.2
    - name: 'arctic_complete_final'
      root_dir: '/home/vin/Doctorat/data/dl_training/raw/Arctic_complete'
      data_dir: '/home/vin/Doctorat/data/dl_training/raw/Arctic_complete'
      tags:
        with_data: True
      split:
        validation: 0.3
        test: 0.2


      # split:
      #   test: 0.2
      #   validation: 0.2
      #   type: "arctic"
        
      
spectrogram:
  type: "mel"
  n_mels: 32
  n_fft: 512
  sample_rate: "original" # For no resampling: remove option or set to original

class_type: "biotic"
classes_file: "/home/vin/Doctorat/dev/dlbd/resources/classes.csv"
reference_classes_file: "/home/vin/Doctorat/dev/dlbd/resources/reference_classes.csv"